---
title: "Jaccard_Index"
author: "Tyrome Sweet"
date: "5/3/2021"
output: html_document
---

```{r setup, include=FALSE}
# Function for Jaccard index
jaccard_change<-function(g1,g2) {
  library(igraph)
  g1<-get.adjacency(g1)
  g1[g1 > 0.001] <- 1
  g2<-get.adjacency(g2)
  g2[g2 > 0.001] <- 1
  Title<-"Numbers represent edges"
  Left<-sum(g1 > g2) # edges that changed (1->0)
  Right<-sum(g1 < g2) # edges that changed (0->1)
  Both<-sum(g1 * g2) # edges that have a 1 in M1 and 1 in M2, so stayed the same (1->1)
  Index<-round(Both/sum(Left,Right,Both),digits = 2) # the ratio of stable ties ties (B), compared to all ties who change (A) + stable ties (B)
  Results<-return(structure(list(Title,Index,Left,Right,Both),names=c("Title","Jaccard_Index","Left_Network_Only", "Right_Network_Only", "Both_Networks")))
  on.exit(rm(Left,Right,Both,Index))
}
```

# Test Data
```{r}
set.seed(1337)
Test_Network_0<-matrix(nrow = 10, ncol = 10)    # 1 row and 1 column per participant
for (i in sample(1:10,13,replace=T)) {          # randomly select a number between 1 and 10, and the same numbers can be used multiple times. We do this 13 times 
  Test_Network_0[i,sample(1:10,1,replace=T)]<-1 # for each randomly selected participant, randomly assign and alter (again, between 1 and 10) to create an edge
}
print(Test_Network_0)
sum(Test_Network_0,na.rm=TRUE)
```
```{r}
Test_Network_2=Test_Network_0
Test_Network_1=Test_Network_0

Test_Network_1[2,8]<-NA
print(Test_Network_1)
Test_Network_2[8,5]<-NA
print(Test_Network_2)
```

```{r}
library(igraph)
# Jaccard index is the total of shared edges divided by the total edges (Shared, Unique)

Test_Graph_1<-graph_from_adjacency_matrix(Test_Network_1, mode = c("directed"))
Test_Graph_2<-graph_from_adjacency_matrix(Test_Network_2, mode = c("directed"))
```

```{r, echo=FALSE}
jaccard_change(Test_Graph_2,Test_Graph_1)
get.edgelist(Test_Graph_2)
```
```{r}
TG1_adjacency<-get.adjacency(Test_Graph_1)
TG2_adjacency<-get.adjacency(Test_Graph_2)
combined_TG_adjacency=TG1_adjacency-TG2_adjacency
print(combined_TG_adjacency)
combined_TG_adjacency2=which(combined_TG_adjacency<0)<-NA
combined_TG_net<-graph_from_adjacency_matrix(combined_TG_adjacency2)
get.edgelist(combined_TG_net)
#print(sum(combined_TG_net))
```
```{r}
Test_Graph_3=Test_Graph_1%m%Test_Graph_2
print(Test_Graph_3)
print(Test_Graph_2)
print(Test_Graph_1)
get.edgelist(Test_Graph_3)
```
# My data
```{r, echo=FALSE}
# make a network out of the matrices
library(igraph)
## 
## Attaching package: 'igraph'
## The following objects are masked from 'package:stats':
## 
##     decompose, spectrum
## The following object is masked from 'package:base':
## 
##     union

#VGAS
#vgas_nodes <- read.csv("/Users/tyromesweet/Documents/GitHub/Going_through_phages/vgasReports/VGAS_CORRECTED2", header=F, as.is=T)
#vgas_links <- read.csv("/Users/tyromesweet/Documents/GitHub/Going_through_phages/vgasReports/VGAS_EDGES2", header=F, as.is=T)

#Prokka
#prokka_nodes <- read.csv("/Users/tyromesweet/Documents/GitHub/Going_through_phages/prokka_5_15_2020/NODES", header=F, as.is=T)
#prokka_links <- read.csv("/Users/tyromesweet/Documents/GitHub/Going_through_phages/prokka_5_15_2020/EDGES", header=F, as.is=T)


vgas_nodes <- read.csv("/home/tsweet/Going_through_phages/vgasReports/VGAS_CORRECTED2", header=F, as.is=T)
vgas_links <- read.csv("/home/tsweet/Going_through_phages/vgasReports/VGAS_EDGES2", header=F, as.is=T)

#Prokka
# prokka_nodes <- read.csv("/home/tsweet/Going_through_phages/prokka_5_15_2020/NODES", header=F, as.is=T)
prokka_nodes <- read.csv("/home/tsweet/Going_through_phages/vgasReports/VGAS_CORRECTED2", header=F, as.is=T)
prokka_links <- read.csv("/home/tsweet/Going_through_phages/prokka_5_15_2020/EDGES", header=F, as.is=T)
```

```{r, echo=FALSE}
head(vgas_nodes)
head(vgas_links)
head(prokka_nodes)
head(prokka_links)
```
```{r, echo=FALSE}
 vgas_adjacency<-get.adjacency(vgas_net)
print(vgas_adjacency)
```
```{r, echo=FALSE}
 prokka_adjacency<-get.adjacency(prokka_net)
print(prokka_adjacency)
```
```{r, echo=FALSE}
vgas_net <- graph_from_data_frame(d=vgas_links, vertices=vgas_nodes, directed=T)
prokka_net <- graph_from_data_frame(d=prokka_links, vertices=prokka_nodes, directed=T)
```

```{r, echo=FALSE}
print(vgas_net)
```
```{r, echo=FALSE}
print(prokka_net)
```

```{r, echo=FALSE}
output=jaccard_change(vgas_net,prokka_net)
print(output)
```

```{r}
prokka_unique=prokka_net%m%vgas_net
get.edgelist(prokka_unique)
write_graph(prokka_unique, "/home/tsweet/Going_through_phages/prokka_unique.txt", "edgelist")
```
```{r}
vgas_unique=vgas_net%m%prokka_net
get.edgelist(vgas_unique)
write_graph(vgas_unique, "/home/tsweet/Going_through_phages/vgas_unique.txt", "edgelist")
```
```{r}
library(igraph)

## Create a wheel graph
wheel <- union(make_ring(10),
                     make_star(11, center=11, mode="undirected"))
V(wheel)$name <- letters[seq_len(vcount(wheel))]

## Subtract a star graph from it
sstar <- make_star(6, center=6, mode="undirected")
V(sstar)$name <- letters[c(1,3,5,7,9,11)]
G <- wheel %m% sstar
print_all(G)
plot(G, layout=layout_nicely(wheel))
```
