---
title: "Network_test"
author: "Tyrome Sweet"
date: "4/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r , echo=FALSE}
library("igraph")
nodes <- read.csv("VGAS_CORRECTED2", header=F, as.is=T)
links <- read.csv("VGAS_EDGES", header=F, as.is=T)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
head(nodes)
head(links)
```

```{r}
VGAS_net <- graph_from_data_frame(d=links, vertices=nodes, directed=T)
VGAS_net <- simplify(VGAS_net, remove.multiple = F, remove.loops = T)
#E(net)$width <- E(net)$weight
deg <- degree(VGAS_net, mode="all")
V(VGAS_net)$size <- deg
VGAS_net
```
```{r}
E(VGAS_net)$width #<- E(net)$weight
```
```{r}
plot(VGAS_net, edge.arrow.size=.1,vertex.size=5,vertex.label=NA, edge.color="red", layout=layout_with_mds)
```

```{r}
plot(VGAS_net, edge.arrow.size=0,vertex.size=5,vertex.label=NA, edge.color="red", layout=layout_with_mds)
```
```{r}
plot(VGAS_net, edge.arrow.size=0, vertex.size=4,vertex.label=NA, edge.color="red")
```

```{r}
plot(VGAS_net, edge.arrow.size=0,vertex.size=6,vertex.label=NA, edge.color="red", layout=layout_with_gem)
```