---
title: "Network_test"
author: "Tyrome Sweet"
date: "4/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
install.packages("igraph") 
install.packages("network") 
install.packages("sna")
install.packages("ggraph")
install.packages("visNetwork")
install.packages("threejs")
install.packages("networkD3")
install.packages("ndtv")
```

```{r , echo=FALSE}
library("igraph")
nodes <- read.csv("NODES", header=F, as.is=T)
links <- read.csv("EDGES", header=F, as.is=T)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
head(nodes)
head(links)
```

```{r}
nodes
```

```{r}
Prokka_net <- graph_from_data_frame(d=links, vertices=nodes, directed=F)
Prokka_net <- simplify(net, remove.multiple = F, remove.loops = T)
#E(net)$width <- E(net)$weight
deg <- degree(Prokka_net, mode="all")
V(Prokka_net)$size <- deg
Prokka_net
```
```{r}
E(Prokka_net)$width #<- E(net)$weight
```
```{r}
plot(Prokka_net, edge.arrow.size=0,vertex.size=5,vertex.label=NA, edge.color="blue", layout=layout_with_gem)
```
```{r}
plot(Prokka_net, edge.arrow.size=0,vertex.size=3,vertex.label=NA, edge.color="blue", layout=layout_with_gem)
```
```{r}
plot(Prokka_net, edge.arrow.size=0,vertex.size=3,vertex.label=NA, edge.color="blue", layout=layout_with_mds)
```

```{r}
# Function for Jaccard index
jaccard_index<-function(g1,g2) {
  library(igraph)
  g1<-get.adjacency(g1)
  g1[g1 > 0.001] <- 1
  g2<-get.adjacency(g2)
  g2[g2 > 0.001] <- 1
  A<-sum(g1 != g2) # edges that changed (0->1 and 1->0)
  B<-sum(g1 * g2) # edges that have a 1 in M1 and 1 in M2, so stayed the same (1->1)
  return(round(B/sum(A,B),digits = 2)) # the ratio of stable ties ties (B), compared to all ties who change (A) + stable ties (B)
  on.exit(rm(A,B))
}
```

```{r}
jaccard_index(Prokka_net,VGAS_net)
```